-- INSERTS DE DADOS CODETRIP

use Codetrip;

-- ESTADOS
INSERT INTO Estado VALUES ('AC', 'Acre');
INSERT INTO Estado VALUES ('AL', 'Alagoas');
INSERT INTO Estado VALUES ('AP', 'Amapá');
INSERT INTO Estado VALUES ('AM', 'Amazonas');
INSERT INTO Estado VALUES ('BA', 'Bahia');
INSERT INTO Estado VALUES ('CE', 'Ceará');
INSERT INTO Estado VALUES ('DF', 'Distrito Federal');
INSERT INTO Estado VALUES ('ES', 'Espírito Santo');
INSERT INTO Estado VALUES ('GO', 'Goiás');
INSERT INTO Estado VALUES ('MA', 'Maranhão');
INSERT INTO Estado VALUES ('MT', 'Mato Grosso');
INSERT INTO Estado VALUES ('MS', 'Mato Grosso do Sul');
INSERT INTO Estado VALUES ('MG', 'Minas Gerais');
INSERT INTO Estado VALUES ('PA', 'Pará');
INSERT INTO Estado VALUES ('PB', 'Paraíba');
INSERT INTO Estado VALUES ('PR', 'Paraná');
INSERT INTO Estado VALUES ('PE', 'Pernambuco');
INSERT INTO Estado VALUES ('PI', 'Piauí');
INSERT INTO Estado VALUES ('RJ', 'Rio de Janeiro');
INSERT INTO Estado VALUES ('RN', 'Rio Grande do Norte');
INSERT INTO Estado VALUES ('RS', 'Rio Grande do Sul');
INSERT INTO Estado VALUES ('RO', 'Rondônia');
INSERT INTO Estado VALUES ('RR', 'Roraima');
INSERT INTO Estado VALUES ('SC', 'Santa Catarina');
INSERT INTO Estado VALUES ('SP', 'São Paulo');
INSERT INTO Estado VALUES ('SE', 'Sergipe');
INSERT INTO Estado VALUES ('TO', 'Tocantins');

-- CIDADES
INSERT INTO Cidade VALUES('Porto Acre', 'AC');
INSERT INTO Cidade VALUES('Rio Branco', 'AC');
INSERT INTO Cidade VALUES('Belém', 'AL');
INSERT INTO Cidade VALUES('Maceió', 'AL');
INSERT INTO Cidade VALUES('Amapá', 'AP');
INSERT INTO Cidade VALUES('Macapá', 'AP');
INSERT INTO Cidade VALUES('Manaus', 'AM');
INSERT INTO Cidade VALUES('São Gabriel da Cachoeira', 'AM');
INSERT INTO Cidade VALUES('Santa Bárbara', 'BA');
INSERT INTO Cidade VALUES('Vitória da Conquista', 'BA');
INSERT INTO Cidade VALUES('Xique-Xique', 'BA');
INSERT INTO Cidade VALUES('Fortaleza', 'CE');
INSERT INTO Cidade VALUES('Sobral', 'CE');
INSERT INTO Cidade VALUES('Santa Teresa', 'ES');
INSERT INTO Cidade VALUES('Serra', 'ES');
INSERT INTO Cidade VALUES('Vitória', 'ES');
INSERT INTO Cidade VALUES('Anápolis', 'GO');
INSERT INTO Cidade VALUES('Bom Jesus de Goiás', 'GO');
INSERT INTO Cidade VALUES('Cidade Ocidental', 'GO');
INSERT INTO Cidade VALUES('Vianópolis', 'GO');
INSERT INTO Cidade VALUES('Vicentinópolis', 'GO');
INSERT INTO Cidade VALUES('Vila Boa', 'GO');
INSERT INTO Cidade VALUES('Afonso Cunha', 'MA');
INSERT INTO Cidade VALUES('Água Doce do Maranhão', 'MA');
INSERT INTO Cidade VALUES('Buriti', 'MA');
INSERT INTO Cidade VALUES('Buriti Bravo', 'MA');
INSERT INTO Cidade VALUES('Buriticupu', 'MA');
INSERT INTO Cidade VALUES('Água Boa', 'MT');
INSERT INTO Cidade VALUES('Alta Floresta', 'MT');
INSERT INTO Cidade VALUES('Alto Araguaia', 'MT');
INSERT INTO Cidade VALUES('Água Clara', 'MS');
INSERT INTO Cidade VALUES('Alcinópolis', 'MS');
INSERT INTO Cidade VALUES('Eldorado', 'MS');
INSERT INTO Cidade VALUES('Açucena', 'MG');
INSERT INTO Cidade VALUES('Águas Formosas', 'MG');
INSERT INTO Cidade VALUES('Barbacena', 'MG');
INSERT INTO Cidade VALUES('Wenceslau Braz', 'MG');
INSERT INTO Cidade VALUES('Cachoeira do Arari', 'PA');
INSERT INTO Cidade VALUES('Cachoeira do Piriá', 'PA');
INSERT INTO Cidade VALUES('Cametá', 'PA');
INSERT INTO Cidade VALUES('Água Branca', 'PB');
INSERT INTO Cidade VALUES('Aguiar', 'PB');
INSERT INTO Cidade VALUES('Alagoa Grande', 'PB');
INSERT INTO Cidade VALUES('Sossêgo', 'PB');
INSERT INTO Cidade VALUES('Pinhão', 'PR');
INSERT INTO Cidade VALUES('Porto Vitória', 'PR');
INSERT INTO Cidade VALUES('Rancho Alegre', 'PR');
INSERT INTO Cidade VALUES('Abreu e Lima', 'PE');
INSERT INTO Cidade VALUES('Afogados da Ingazeira', 'PE');
INSERT INTO Cidade VALUES('Afrânio', 'PE');
INSERT INTO Cidade VALUES('Betânia', 'PE');
INSERT INTO Cidade VALUES('Bezerros', 'PE');
INSERT INTO Cidade VALUES('Bodocó', 'PE');
INSERT INTO Cidade VALUES('Vitória de Santo Antão', 'PE');
INSERT INTO Cidade VALUES('Acauã', 'PI');
INSERT INTO Cidade VALUES('Redenção do Gurguéia', 'PI');
INSERT INTO Cidade VALUES('Regeneração', 'PI');
INSERT INTO Cidade VALUES('Riacho Frio', 'PI');
INSERT INTO Cidade VALUES('São João do Arraial', 'PI');
INSERT INTO Cidade VALUES('Angra dos Reis', 'RJ');
INSERT INTO Cidade VALUES('Armação dos Búzios', 'RJ');
INSERT INTO Cidade VALUES('Arraial do Cabo', 'RJ');
INSERT INTO Cidade VALUES('Macaé', 'RJ');
INSERT INTO Cidade VALUES('Nova Friburgo', 'RJ');
INSERT INTO Cidade VALUES('Rio Bonito', 'RJ');
INSERT INTO Cidade VALUES('São Fidélis', 'RJ');
INSERT INTO Cidade VALUES('São Gonçalo', 'RJ');
INSERT INTO Cidade VALUES('Volta Redonda', 'RJ');
INSERT INTO Cidade VALUES('Acari', 'RN');
INSERT INTO Cidade VALUES('Serrinha dos Pintos', 'RN');
INSERT INTO Cidade VALUES('Várzea', 'RN');
INSERT INTO Cidade VALUES('Vera Cruz', 'RN');
INSERT INTO Cidade VALUES('Aceguá', 'RS');
INSERT INTO Cidade VALUES('Água Santa', 'RS');
INSERT INTO Cidade VALUES('Tenente Portela', 'RS');
INSERT INTO Cidade VALUES('Tunas', 'RS');
INSERT INTO Cidade VALUES('Alta Floresta d''Oeste', 'RO');
INSERT INTO Cidade VALUES('Nova Brasilândia d''Oeste', 'RO');
INSERT INTO Cidade VALUES('Nova Mamoré', 'RO');
INSERT INTO Cidade VALUES('Nova União', 'RO');
INSERT INTO Cidade VALUES('Novo Horizonte do Oeste', 'RO');
INSERT INTO Cidade VALUES('Ouro Preto do Oeste', 'RO');
INSERT INTO Cidade VALUES('Alto Alegre', 'RR');
INSERT INTO Cidade VALUES('Bonfim', 'RR');
INSERT INTO Cidade VALUES('Normandia', 'RR');
INSERT INTO Cidade VALUES('São Luiz', 'RR');
INSERT INTO Cidade VALUES('Abelardo Luz', 'SC');
INSERT INTO Cidade VALUES('Águas de Chapecó', 'SC');
INSERT INTO Cidade VALUES('Bom Retiro', 'SC');
INSERT INTO Cidade VALUES('São Miguel da Boa Vista', 'SC');
INSERT INTO Cidade VALUES('Tubarão', 'SC');
INSERT INTO Cidade VALUES('São Paulo', 'SP');
INSERT INTO Cidade VALUES('Guarulhos', 'SP');
INSERT INTO Cidade VALUES('São Bernardo do Campo', 'SP');
INSERT INTO Cidade VALUES('Osasco', 'SP');
INSERT INTO Cidade VALUES('Bertioga', 'SP');
INSERT INTO Cidade VALUES('Cubatão', 'SP');
INSERT INTO Cidade VALUES('Guarujá', 'SP');
INSERT INTO Cidade VALUES('Itanhaém', 'SP');
INSERT INTO Cidade VALUES('Mongaguá', 'SP');
INSERT INTO Cidade VALUES('Peruíbe', 'SP');
INSERT INTO Cidade VALUES('Praia Grande', 'SP');
INSERT INTO Cidade VALUES('Santos', 'SP');
INSERT INTO Cidade VALUES('São Vicente', 'SP');
INSERT INTO Cidade VALUES('Cananéia', 'SP');
INSERT INTO Cidade VALUES('Ilha Comprida', 'SP');
INSERT INTO Cidade VALUES('Iguape', 'SP');
INSERT INTO Cidade VALUES('Amparo de São Francisco', 'SE');
INSERT INTO Cidade VALUES('Arauá', 'SE');
INSERT INTO Cidade VALUES('Salgado', 'SE');
INSERT INTO Cidade VALUES('São Domingos', 'SE');
INSERT INTO Cidade VALUES('São Francisco', 'SE');
INSERT INTO Cidade VALUES('Abreulândia', 'TO');
INSERT INTO Cidade VALUES('Itaguatins', 'TO');
INSERT INTO Cidade VALUES('Itapiratins', 'TO');
INSERT INTO Cidade VALUES('Itaporã do Tocantins', 'TO');

-- TIPO DE HOSPEDAGEM
INSERT INTO Tipo_Pensao (Desc_Pensao, Valor_Pensao) VALUES ('Nenhuma', 0.00);
INSERT INTO Tipo_Pensao (Desc_Pensao, Valor_Pensao) VALUES ('Meia pensão (Café da manhã e Almoço)', 100.00);
INSERT INTO Tipo_Pensao (Desc_Pensao, Valor_Pensao) VALUES ('Pensão completa (Café, Almoço e Jantar)', 180.00);

-- TIPOS DE TRANSPORTE
INSERT INTO Transporte (Tipo_Transp, UF_Estado) VALUES ('Táxi', 'AC');
INSERT INTO Transporte (Tipo_Transp, UF_Estado) VALUES ('Táxi', 'AL');
INSERT INTO Transporte (Tipo_Transp, UF_Estado) VALUES ('Táxi', 'AP');
INSERT INTO Transporte (Tipo_Transp, UF_Estado) VALUES ('Táxi', 'AM');
INSERT INTO Transporte (Tipo_Transp, UF_Estado) VALUES ('Táxi', 'BA');
INSERT INTO Transporte (Tipo_Transp, UF_Estado) VALUES ('Táxi', 'CE');
INSERT INTO Transporte (Tipo_Transp, UF_Estado) VALUES ('Táxi', 'DF');
INSERT INTO Transporte (Tipo_Transp, UF_Estado) VALUES ('Táxi', 'ES');
INSERT INTO Transporte (Tipo_Transp, UF_Estado) VALUES ('Táxi', 'GO');
INSERT INTO Transporte (Tipo_Transp, UF_Estado) VALUES ('Táxi', 'MA');
INSERT INTO Transporte (Tipo_Transp, UF_Estado) VALUES ('Táxi', 'MT');
INSERT INTO Transporte (Tipo_Transp, UF_Estado) VALUES ('Táxi', 'MS');
INSERT INTO Transporte (Tipo_Transp, UF_Estado) VALUES ('Táxi', 'MG');
INSERT INTO Transporte (Tipo_Transp, UF_Estado) VALUES ('Táxi', 'PA');
INSERT INTO Transporte (Tipo_Transp, UF_Estado) VALUES ('Táxi', 'PB');
INSERT INTO Transporte (Tipo_Transp, UF_Estado) VALUES ('Táxi', 'PR');
INSERT INTO Transporte (Tipo_Transp, UF_Estado) VALUES ('Táxi', 'PE');
INSERT INTO Transporte (Tipo_Transp, UF_Estado) VALUES ('Táxi', 'PI');
INSERT INTO Transporte (Tipo_Transp, UF_Estado) VALUES ('Táxi', 'RJ');
INSERT INTO Transporte (Tipo_Transp, UF_Estado) VALUES ('Táxi', 'RN');
INSERT INTO Transporte (Tipo_Transp, UF_Estado) VALUES ('Táxi', 'RS');
INSERT INTO Transporte (Tipo_Transp, UF_Estado) VALUES ('Táxi', 'RO');
INSERT INTO Transporte (Tipo_Transp, UF_Estado) VALUES ('Táxi', 'RR');
INSERT INTO Transporte (Tipo_Transp, UF_Estado) VALUES ('Táxi', 'SC');
INSERT INTO Transporte (Tipo_Transp, UF_Estado) VALUES ('Táxi', 'SP');
INSERT INTO Transporte (Tipo_Transp, UF_Estado) VALUES ('Táxi', 'SE');
INSERT INTO Transporte (Tipo_Transp, UF_Estado) VALUES ('Táxi', 'TO');
INSERT INTO Transporte (Tipo_Transp, UF_Estado) VALUES ('Ônibus', 'AC');
INSERT INTO Transporte (Tipo_Transp, UF_Estado) VALUES ('Ônibus', 'AL');
INSERT INTO Transporte (Tipo_Transp, UF_Estado) VALUES ('Ônibus', 'AP');
INSERT INTO Transporte (Tipo_Transp, UF_Estado) VALUES ('Ônibus', 'AM');
INSERT INTO Transporte (Tipo_Transp, UF_Estado) VALUES ('Ônibus', 'BA');
INSERT INTO Transporte (Tipo_Transp, UF_Estado) VALUES ('Ônibus', 'CE');
INSERT INTO Transporte (Tipo_Transp, UF_Estado) VALUES ('Ônibus', 'DF');
INSERT INTO Transporte (Tipo_Transp, UF_Estado) VALUES ('Ônibus', 'ES');
INSERT INTO Transporte (Tipo_Transp, UF_Estado) VALUES ('Ônibus', 'GO');
INSERT INTO Transporte (Tipo_Transp, UF_Estado) VALUES ('Ônibus', 'MA');
INSERT INTO Transporte (Tipo_Transp, UF_Estado) VALUES ('Ônibus', 'MT');
INSERT INTO Transporte (Tipo_Transp, UF_Estado) VALUES ('Ônibus', 'MS');
INSERT INTO Transporte (Tipo_Transp, UF_Estado) VALUES ('Ônibus', 'MG');
INSERT INTO Transporte (Tipo_Transp, UF_Estado) VALUES ('Ônibus', 'PA');
INSERT INTO Transporte (Tipo_Transp, UF_Estado) VALUES ('Ônibus', 'PB');
INSERT INTO Transporte (Tipo_Transp, UF_Estado) VALUES ('Ônibus', 'PR');
INSERT INTO Transporte (Tipo_Transp, UF_Estado) VALUES ('Ônibus', 'PE');
INSERT INTO Transporte (Tipo_Transp, UF_Estado) VALUES ('Ônibus', 'PI');
INSERT INTO Transporte (Tipo_Transp, UF_Estado) VALUES ('Ônibus', 'RJ');
INSERT INTO Transporte (Tipo_Transp, UF_Estado) VALUES ('Ônibus', 'RN');
INSERT INTO Transporte (Tipo_Transp, UF_Estado) VALUES ('Ônibus', 'RS');
INSERT INTO Transporte (Tipo_Transp, UF_Estado) VALUES ('Ônibus', 'RO');
INSERT INTO Transporte (Tipo_Transp, UF_Estado) VALUES ('Ônibus', 'RR');
INSERT INTO Transporte (Tipo_Transp, UF_Estado) VALUES ('Ônibus', 'SC');
INSERT INTO Transporte (Tipo_Transp, UF_Estado) VALUES ('Ônibus', 'SP');
INSERT INTO Transporte (Tipo_Transp, UF_Estado) VALUES ('Ônibus', 'SE');
INSERT INTO Transporte (Tipo_Transp, UF_Estado) VALUES ('Ônibus', 'TO');
INSERT INTO Transporte (Tipo_Transp, UF_Estado) VALUES ('Avião', 'SP');
INSERT INTO Transporte (Tipo_Transp, UF_Estado) VALUES ('Avião', 'SP');
INSERT INTO Transporte (Tipo_Transp, UF_Estado) VALUES ('Avião', 'DF');
INSERT INTO Transporte (Tipo_Transp, UF_Estado) VALUES ('Avião', 'RJ');
INSERT INTO Transporte (Tipo_Transp, UF_Estado) VALUES ('Avião', 'SP');
INSERT INTO Transporte (Tipo_Transp, UF_Estado) VALUES ('Avião', 'MG');
INSERT INTO Transporte (Tipo_Transp, UF_Estado) VALUES ('Avião', 'PE');
INSERT INTO Transporte (Tipo_Transp, UF_Estado) VALUES ('Avião', 'BA');
INSERT INTO Transporte (Tipo_Transp, UF_Estado) VALUES ('Avião', 'RJ');
INSERT INTO Transporte (Tipo_Transp, UF_Estado) VALUES ('Avião', 'PR');
INSERT INTO Transporte (Tipo_Transp, UF_Estado) VALUES ('Avião', 'CE');
INSERT INTO Transporte (Tipo_Transp, UF_Estado) VALUES ('Avião', 'SC');
INSERT INTO Transporte (Tipo_Transp, UF_Estado) VALUES ('Avião', 'PA');
INSERT INTO Transporte (Tipo_Transp, UF_Estado) VALUES ('Avião', 'GO');
INSERT INTO Transporte (Tipo_Transp, UF_Estado) VALUES ('Avião', 'RS');
INSERT INTO Transporte (Tipo_Transp, UF_Estado) VALUES ('Avião', 'ES');
INSERT INTO Transporte (Tipo_Transp, UF_Estado) VALUES ('Avião', 'AM');
INSERT INTO Transporte (Tipo_Transp, UF_Estado) VALUES ('Avião', 'MT');
INSERT INTO Transporte (Tipo_Transp, UF_Estado) VALUES ('Avião', 'AL');
INSERT INTO Transporte (Tipo_Transp, UF_Estado) VALUES ('Avião', 'RN');
INSERT INTO Transporte (Tipo_Transp, UF_Estado) VALUES ('Navio', 'SP');
INSERT INTO Transporte (Tipo_Transp, UF_Estado) VALUES ('Navio', 'RJ'); 
INSERT INTO Transporte (Tipo_Transp, UF_Estado) VALUES ('Navio', 'BA');
INSERT INTO Transporte (Tipo_Transp, UF_Estado) VALUES ('Navio', 'AL');
INSERT INTO Transporte (Tipo_Transp, UF_Estado) VALUES ('Navio', 'PE');
INSERT INTO Transporte (Tipo_Transp, UF_Estado) VALUES ('Navio', 'CE');
INSERT INTO Transporte (Tipo_Transp, UF_Estado) VALUES ('Navio', 'RN');
INSERT INTO Transporte (Tipo_Transp, UF_Estado) VALUES ('Navio', 'PA');
INSERT INTO Transporte (Tipo_Transp, UF_Estado) VALUES ('Navio', 'AM');
INSERT INTO Transporte (Tipo_Transp, UF_Estado) VALUES ('Navio', 'SC');
-- Obs. Taxi - Todos os estados
-- Obs. Onibus - Todos os estados
-- Obs. Avião - Principais aeroportos do Brasil
-- Obs. Navio - Principais portos de passageiros do Brasil
-- Aeroporto Internacional de Natal (NAT), Aeroporto Internacional de Maceió (MCZ), Aeroporto Internacional de Cuiabá (CGB), Aeroporto Internacional de Manaus (MAO), Aeroporto Internacional de Vitória (VIX), Aeroporto Internacional de Porto Alegre (POA), Aeroporto Internacional de Goiânia (GYN), Aeroporto Internacional de Belém (BEL), Aeroporto Internacional de Florianópolis (FLN), Aeroporto Internacional de Fortaleza (FOR), Aeroporto Internacional de Curitiba (CWB), Aeroporto Santos Dumont (SDU), Aeroporto Internacional de Salvador (SSA), Aeroporto Internacional do Recife (REC), Aeroporto Internacional de Confins (CNF), Aeroporto Internacional de Viracopos (VCP), Aeroporto Internacional do Galeão (GIG),  Aeroporto Internacional de Brasília (BSB), Aeroporto de Congonhas (CGH), Aeroporto Internacional de Guarulhos (GRU)
-- Porto de Itajaí, Porto de Manaus, Porto de Belém, Porto de Natal, Porto de Fortaleza, Porto de Recife, Porto de Maceió, Porto de Salvador, Pier Mauá (Rio de Janeiro), Porto de Santos

-- PAGAMENTO
INSERT INTO Pagamento VALUES (NULL, 'Dinheiro');
INSERT INTO Pagamento VALUES (NULL, 'Cartão de Débito');
INSERT INTO Pagamento VALUES (NULL, 'Cartão de Crédito');
INSERT INTO Pagamento VALUES (NULL, 'Transferência Bancária');
INSERT INTO Pagamento VALUES (NULL, 'Pix');
INSERT INTO Pagamento VALUES (NULL, 'Boleto Bancário');

-- TIPOS DE HOSPEDAGENS
INSERT INTO Tipo_Hospedagem VALUES (NULL, 'Single (Solteiro)', 1, 100.00);
INSERT INTO Tipo_Hospedagem VALUES (NULL, 'Double (Solteiro)', 2, 150.00);
INSERT INTO Tipo_Hospedagem VALUES (NULL, 'Double (Casal)', 2, 150.00);
INSERT INTO Tipo_Hospedagem VALUES (NULL, 'Triple (Solteiro)', 3, 250.00);
INSERT INTO Tipo_Hospedagem VALUES (NULL, 'Quadruplo (Solteiro)', 4, 300.00);
INSERT INTO Tipo_Hospedagem VALUES (NULL, 'Família', 6, 400.00);
INSERT INTO Tipo_Hospedagem VALUES (NULL, 'Corporativo Single', 1, 130.00);
INSERT INTO Tipo_Hospedagem VALUES (NULL, 'Corporativo Double', 2, 150.00);